language: node_js
node_js:
  - '6'

before_install:
  - openssl aes-256-cbc -K $encrypted_de02db4d389f_key -iv $encrypted_de02db4d389f_iv -in deploy-key.enc -out ~/.ssh/id_ecdsa -d

# (by default, Travis will run "yarn test" script when the language is node_js)

# deploy is run after "yarn test"
deploy:
  # keep the build we just made with "yarn test" (dist/)
  skip_cleanup: true

  # define the script to use for deployment
  provider: script
  script: ./deploy.sh

  # only run on one version of node (v5 here)
  on:
    branch: src
    node: '6'

env:
  global:
    - GIT_DEPLOY_REPO=git@github.com:mirabit-ua/mirabit-ua.github.io.git
